/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package utama;

import customer.Fcustomer;
import depot.Fdepot;
import hirepoint.Fhirepoint;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import mobil.Fmobil;
import transaksi.Ftransaksi;

/**
 *
 * @author Aldy Senda
 */
public class Futama extends javax.swing.JFrame {

    /**
     * Creates new form frameutama
     */
    public Futama() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuLaporan = new javax.swing.JMenu();
        dataTransaksi = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        dataCustomer = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        dataMobil = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        dataDepot = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        dataHirepoin = new javax.swing.JMenuItem();
        menuAbout = new javax.swing.JMenu();
        menuKeluar = new javax.swing.JMenu();
        keluar = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelUtama.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        menuLaporan.setText("Laporan");
        menuLaporan.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        dataTransaksi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, 0));
        dataTransaksi.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        dataTransaksi.setText("Data Transaksi");
        dataTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataTransaksiActionPerformed(evt);
            }
        });
        menuLaporan.add(dataTransaksi);
        menuLaporan.add(jSeparator4);

        dataCustomer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, 0));
        dataCustomer.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        dataCustomer.setText("Data Customer");
        dataCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataCustomerActionPerformed(evt);
            }
        });
        menuLaporan.add(dataCustomer);
        menuLaporan.add(jSeparator1);

        dataMobil.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, 0));
        dataMobil.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        dataMobil.setText("Data Mobil");
        dataMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataMobilActionPerformed(evt);
            }
        });
        menuLaporan.add(dataMobil);
        menuLaporan.add(jSeparator2);

        dataDepot.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, 0));
        dataDepot.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        dataDepot.setText("Data Depot");
        dataDepot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataDepotActionPerformed(evt);
            }
        });
        menuLaporan.add(dataDepot);
        menuLaporan.add(jSeparator3);

        dataHirepoin.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, 0));
        dataHirepoin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        dataHirepoin.setText("Data Hirepoin");
        dataHirepoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dataHirepoinActionPerformed(evt);
            }
        });
        menuLaporan.add(dataHirepoin);

        jMenuBar1.add(menuLaporan);

        menuAbout.setText("About Us");
        menuAbout.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jMenuBar1.add(menuAbout);

        menuKeluar.setText("Keluar");
        menuKeluar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N

        keluar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        keluar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        keluar.setSelected(true);
        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        menuKeluar.add(keluar);

        jMenuBar1.add(menuKeluar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelUtama)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        if (JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin Ingin Keluar?", "Terima Kasih Atas Perhatiannya", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
        System.exit(0);
  }
    }//GEN-LAST:event_keluarActionPerformed

    private void dataDepotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataDepotActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll(); 
        panelUtama.repaint();
        Fdepot depot = new Fdepot();
        
        //ambil sizescreen
        Dimension layarutama =  this.getSize();
        Dimension layardepot = depot.getSize();
        
        //simpan posisi frame mhs ditengah
        depot.setLocation(layarutama.width/2-layardepot.width/2, layarutama.height/2-layardepot.height/2 );
        
         panelUtama.add(depot); 
         depot.setVisible(true);
    }//GEN-LAST:event_dataDepotActionPerformed

    private void dataTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataTransaksiActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll(); 
        panelUtama.repaint();
        Ftransaksi transaksi = new Ftransaksi();
        
        //ambil sizescreen
        Dimension layarutama =  this.getSize();
        Dimension layartransaksi = transaksi.getSize();
        
        //simpan posisi frame mhs ditengah
        transaksi.setLocation(layarutama.width/2-layartransaksi.width/2, layarutama.height/2-layartransaksi.height/2 );
        
         panelUtama.add(transaksi); 
         transaksi.setVisible(true);
    }//GEN-LAST:event_dataTransaksiActionPerformed

    private void dataCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataCustomerActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll(); 
        panelUtama.repaint();
        Fcustomer customer = new Fcustomer();
        
        //ambil sizescreen
        Dimension layarutama =  this.getSize();
        Dimension layarcustomer = customer.getSize();
        
        //simpan posisi frame mhs ditengah
        customer.setLocation(layarutama.width/2-layarcustomer.width/2, layarutama.height/2-layarcustomer.height/2 );
        
         panelUtama.add(customer); 
         customer.setVisible(true);
    }//GEN-LAST:event_dataCustomerActionPerformed

    private void dataMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataMobilActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll(); 
        panelUtama.repaint();
        Fmobil mobil = new Fmobil();
        
        //ambil sizescreen
        Dimension layarutama =  this.getSize();
        Dimension layarmobil = mobil.getSize();
        
        //simpan posisi frame mhs ditengah
        mobil.setLocation(layarutama.width/2-layarmobil.width/2, layarutama.height/2-layarmobil.height/2 );
        
         panelUtama.add(mobil); 
         mobil.setVisible(true);
    }//GEN-LAST:event_dataMobilActionPerformed

    private void dataHirepoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dataHirepoinActionPerformed
        // TODO add your handling code here:
        panelUtama.removeAll(); 
        panelUtama.repaint();
        Fhirepoint hirepoint = new Fhirepoint();
        
        //ambil sizescreen
        Dimension layarutama =  this.getSize();
        Dimension layarhirepoint = hirepoint.getSize();
        
        //simpan posisi frame mhs ditengah
        hirepoint.setLocation(layarutama.width/2-layarhirepoint.width/2, layarutama.height/2-layarhirepoint.height/2 );
        
         panelUtama.add(hirepoint); 
         hirepoint.setVisible(true);
    }//GEN-LAST:event_dataHirepoinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Futama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Futama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Futama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Futama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Futama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem dataCustomer;
    private javax.swing.JMenuItem dataDepot;
    private javax.swing.JMenuItem dataHirepoin;
    private javax.swing.JMenuItem dataMobil;
    private javax.swing.JMenuItem dataTransaksi;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JCheckBoxMenuItem keluar;
    private javax.swing.JMenu menuAbout;
    private javax.swing.JMenu menuKeluar;
    private javax.swing.JMenu menuLaporan;
    private javax.swing.JDesktopPane panelUtama;
    // End of variables declaration//GEN-END:variables
}
